### PR TITLE
Main

### PR DESCRIPTION
**Pull request by snehas-05**
Feature- Interactive cybersecurity quiz 
The quiz covers various important topics through multiple-choice questions. Users get instant feedback on their answers, helping them learn as they go, and can track their progress over time. A leaderboard is included to encourage some friendly competition, and after completing the quiz, users can explore helpful resources also. The quiz is designed to be easy to use, responsive, and engaging for all users.
For better understanding of the code, I have added a separate folder named as interactive_quiz consisting of files index.html, styles.css, quiz.js
I request you to to kindly merge my code. I will be grateful to you.

### CODE REVIEW

**Comment by B1N4RY-P4R45173** [comment]
Hi Thanks for the PR
If you want, you can mention the issue number you're addressing in your PR using one of several keywords and GitHub will automatically link them together for you.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by snehas-05** [comment]
Hey @B1N4RY-P4R45173 you asked me about my issue number and all but you had not merged my pr yet..Is there any specific reason for the same?

**Comment by B1N4RY-P4R45173** [comment]
@Vinay-Khanagavi  Can you please check and review this?
Also @snehas-05 you have to update the repo and resolve conflicts for us to be able to merge your pr

**Comment by snehas-05** [comment]
Is there any issue?

**Comment by B1N4RY-P4R45173** [comment]
I don't see any issue but the right person to comment on this is @Vinay-Khanagavi. Since he is looking after these kinds of issues
As of now you just need to sync your repo with the current commits without which we cannot merge. You can refer to 
https://www.atlassian.com/git/tutorials/merging-vs-rebasing if you don't know how to do it. And for the review pls wait till Monday. If @Vinay-Khanagavi doesn't respond by then I will review it. Sorry for this delay.

**Comment by snehas-05** [comment]
Okay no issues. I will sync the changes after going through the steps once from the link you provided.

**Comment by snehas-05** [comment]
Hey @B1N4RY-P4R45173 I have synced my repo can you please check once?

**Pull request closed without merging**
