### PR TITLE
fixed UI icons for small device

### PR DESCRIPTION
**Pull request by IshuSinghSE**
This PR Closes: #49 issue
- [x] Added menu for easily navigate to the pages

Please let me know for any changes required.

### CODE REVIEW

**Comment by Vinay-Khanagavi** [comment]
@IshuSinghSE Can you share the screenshot in discussion #16

**Comment by B1N4RY-P4R45173** [comment]
@IshuSinghSE thanks for this pr. It looks great. But I think a few things could be improved.

firstly, Clicking second time on the toggle icon can set display to set the display of icon container to none, so that users doesn't have to click somewhere on the screen

Secondly, for devices with large display we don't need the display toggle

Lastly, for smaller display make sure that the  levels and their description is displayed in correct order

**Comment by B1N4RY-P4R45173** [comment]
@Vinay-Khanagavi Here you go

{A59EFC87-9A61-4BF8-98A1-52C6B09743E9}

{C8C14E02-5DBA-4F37-A105-5216720DAE8A}

{68D08A34-8999-4A28-96DF-244CCC31CB8E}

{C4B6D97E-44BE-468C-B7BD-854F2A62B650}

**Comment by B1N4RY-P4R45173** [comment]
Also @IshuSinghSE 

Align the contents to center so that the icons wont cover the contents

**Comment by IshuSinghSE** [comment]
> Also @IshuSinghSE
> 
> Align the contents to center so that the icons wont cover the contents

I will surely do the adjustments!
Thanks for the feedback

**Comment by B1N4RY-P4R45173** [comment]
are you still working on this @IshuSinghSE ?

**Comment by IshuSinghSE** [comment]
> are you still working on this @IshuSinghSE ?

I am stuck, because I am unable to see Resolve conflicts here, but there are conflicts

**Comment by IshuSinghSE** [comment]
Now I have fixed the elemetns of homepage.
127 0 0 1_5500_index html

**Comment by B1N4RY-P4R45173** [comment]
@IshuSinghSE  I will check it tmrw. And yeah most of the times to resolve conflicts u have to rebase it. I hope u figured it by now, sry for the late response.

**Comment by IshuSinghSE** [comment]
> @IshuSinghSE I will check it tmrw. And yeah most of the times to resolve conflicts u have to rebase it. I hope u figured it by now, sry for the late response.

No Problem 😁,

- [x] I have resolved all the conflicts
- [x] I have made the necessary changes for large and small devices

please review and merge the PR!

**Comment by B1N4RY-P4R45173** [comment]
@IshuSinghSE 

That's some nice improvement but I think the UI could be more better.
{1B19C8A7-A2F3-483F-A0D1-E708417443D5}

starting with above screenshot, the heading (Level1 and play button) should be above the content (abt phishing attacks)

{5BDFA3F4-19F2-49B2-8222-269AAF78878E}

Here you can again set the headings and play button to the center for level 2 and 3.

Follow the order of 
- heading (level number and play button) 
- then the content (what is about) 
- and then the video 

follow the same order for same order

**Pull request closed without merging**
