### PR TITLE
Made the modification

### PR DESCRIPTION
**Pull request by Dipanita45**
Add more transition, bold the text , colour and ,..etc  , added or updated the fetures of the website

Issue no : #9 

Thank you giving chance
Thank you for the support @Vinay-Khanagavi sir
Please review my pull request and label  level 2

### CODE REVIEW

**Comment by Vinay-Khanagavi** [comment]
Looks good but for label level 2 you need make the homepage responsive can you doo that !?

### **Task** 
the description of level should overlay under the gif : Make it responsive in mobile

format in mobile :
- Level 1
- GIF
- Description
- Play Button
same with other levels

image

**Comment by Dipanita45** [comment]
I will try

**Comment by Vinay-Khanagavi** [comment]
pull the project and remove the conflicts

**Comment by Dipanita45** [comment]
This conflicts cant be resolved as this file is removed from the projects as it is not showing 
Please lebel me level 2 @Vinay-Khanagavi

**Comment by Vinay-Khanagavi** [comment]
@Dipanita45  https://discord.gg/wFWtpVmB 

Join the above discord server and there create a post : `Made the modification #10`

**Comment by Dipanita45** [comment]
Create the post

**Comment by B1N4RY-P4R45173** [comment]
Please close this pr if you have made a new pr for the same issue

**Comment by Dipanita45** [comment]
Please check and label me for pr:10 whatever it is okay

**Pull request closed without merging**
