### PR TITLE
Solved issue #6

### PR DESCRIPTION
**Pull request by ragini-gp**
I have created folders to separate level_index, css, aui files
image

Added scroll to top button
image

### CODE REVIEW

**Comment by Vinay-Khanagavi** [comment]
This makes the code so much cleaner now!  Thanks for your contribution

**Comment by ragini-gp** [comment]
Please assign hacktoberfest-accepted label as well

**Comment by Vinay-Khanagavi** [comment]
@ragini-gp  can you check the navigation again because it is not working

**Comment by ragini-gp** [comment]
Okay

**Comment by Vinay-Khanagavi** [comment]
I corrected the navigation part just make sure level_2 is outside

**Comment by ragini-gp** [comment]
Actually, these folders, I did not create, these were already there, and are so confusing, so, I didn't touch them

**Comment by Vinay-Khanagavi** [comment]
oh it's fine, I'll let my teammate do this task. thanks you

**Comment by ragini-gp** [comment]
Thankyou

**Pull request merged**
