### PR TITLE
Update the modification

### PR DESCRIPTION
**Pull request by Dipanita45**
Add or update the css properties  in the responsive side and in the website to make more attractive

Fixes issue : #9 

Please review my pull request and label me @Vinay-Khanagavi 
Thank you for the chance to contribute

### CODE REVIEW

**Comment by Dipanita45** [comment]
Okay

**Comment by Dipanita45** [comment]
Please review my pull request @Vinay-Khanagavi  and level me
I have fixed the issue

**Comment by Dipanita45** [comment]
Screenshot 2024-10-19 113556
please review my pull request and label me level 2 
@Vinay-Khanagavi 
Thank you for the chance

**Comment by B1N4RY-P4R45173** [comment]
{8A8C25B1-B457-49A2-9D1F-BDCF3D4FB151}
We don't want the black background for the text

**Comment by Dipanita45** [comment]
Please label me

**Comment by Dipanita45** [comment]
I will fixed it

**Comment by Dipanita45** [comment]
WhatsApp Image 2024-10-19 at 06 29 35_f90688ae
Please review the pull level and merge it and label it level 2
@Vinay-Khanagavi @B1N4RY-P4R45173 
Thank you for the chance

**Comment by B1N4RY-P4R45173** [comment]
Lmao no need to write thankyou for the chance every time @Dipanita45 
We are also clg students with a passion to design and develop things so there is no need to maintain that high level of formaility with us. Also I don't see the screenshot that you attached?

> Uploading Screenshot 2024-10-19 125532.png…

**Comment by Dipanita45** [comment]
Okay

**Comment by Dipanita45** [comment]
Please merge my pull request

**Comment by Dipanita45** [comment]
Screenshot 2024-10-19 125532

**Comment by Vinay-Khanagavi** [comment]
The good thing you did is adding hover effects, media queries, and text alignment adjustments. 
Remove all changes except this i will merge it

**Comment by Dipanita45** [comment]
Please review the pull request and merge it and label me level 2 please

**Pull request merged**
