### PR TITLE
Added cyber quiz app with gemini

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
Closes: #26

Deployed URL: https://cyber-quiz-app.vercel.app/

### CODE REVIEW

**Comment by J-B-Mugundh** [comment]
@B1N4RY-P4R45173 Please check the deployed URL. Questions will be beginner friendly as you expect. Also, consider moving the level up if the work is good.

**Comment by B1N4RY-P4R45173** [comment]
@J-B-Mugundh That's some great work. I have increased to level3 as u requested. But before merging I have a few things that I would like to discuss with you. Can you create a new post in issues channel in our discord server

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh That's some great work. I have increased to level3 as u requested. But before merging I have a few things that I would like to discuss with you. Can you create a new post in issues channel in our discord server

Yeah sure!

**Comment by J-B-Mugundh** [comment]
> Hey @J-B-Mugundh ,
> 
> Thank you so much for your hard work on the PR and your interest in contributing to the project! However, we've decided not to merge it at this time because we're currently focused on completing the_ project using HTML, CSS, and JavaScript. 
> 
> Once we reach that milestone, we plan to convert the project into a Next.js app. Our goal is to eventually create an organization with multiple repositories, and when that happens, your quiz app can be pushed into a dedicated repo where it can be properly integrated. For now, we want to avoid having multiple linked platforms, like hosting on Vercel and linking to different URLs, which isn't ideal for our future domain setup. 
> 
> Thanks for your understanding, and we hope to collaborate with you again when we're ready for that next step!
> 

@Vinay-Khanagavi atleast you could merge the PR for my work and revert it right? Gssoc-extd would end in 10 days. I've spent time on working and deploying as well.

**Comment by J-B-Mugundh** [comment]
@Vinay-Khanagavi @B1N4RY-P4R45173 Guys? 

> > Hey @J-B-Mugundh ,
> > Thank you so much for your hard work on the PR and your interest in contributing to the project! However, we've decided not to merge it at this time because we're currently focused on completing the_ project using HTML, CSS, and JavaScript.
> > Once we reach that milestone, we plan to convert the project into a Next.js app. Our goal is to eventually create an organization with multiple repositories, and when that happens, your quiz app can be pushed into a dedicated repo where it can be properly integrated. For now, we want to avoid having multiple linked platforms, like hosting on Vercel and linking to different URLs, which isn't ideal for our future domain setup.
> > Thanks for your understanding, and we hope to collaborate with you again when we're ready for that next step!
> 
> @Vinay-Khanagavi atleast you could merge the PR for my work and revert it back if it's not gonnabe use as of now and then add it when u want right? Gssoc-extd would end in 10 days. I've spent time on working and deploying as well. We even discussed in discord and i worked just after I was told to proceed.
> 
> image
> 
> https://discord.com/channels/1295845717914550363/1296097990225956996

@B1N4RY-P4R45173 @Vinay-Khanagavi Guys?

**Pull request closed without merging**
