### PR TITLE
fix video responsiveness on level 1, 2 and 3

### PR DESCRIPTION
**Pull request by Raj100**
Merge Request to solve issue #143 
- fixed the video too small issue by adding a media query by changing only the flex direction
- Does Not effect the current web design

Screenshots:
Screenshot 2024-10-29 at 1 05 11 AM

Screenshot 2024-10-29 at 12 55 38 AM

Screenshot 2024-10-29 at 1 05 56 AM

### CODE REVIEW

**Comment by Raj100** [comment]
@Vinay-Khanagavi

**Comment by Vinay-Khanagavi** [comment]
Please Update your branch..

**Comment by Raj100** [comment]
I have checked the code is up to date with the current main branch. And the merge request will only affect 3 files

main/level_1/phishing_animated_video.html
main/level_2/phishing_animated_video.html
main/level_3/phishing_animated_video.html

No other files will be affected if fix was made on some other file

**Comment by Raj100** [comment]
Screenshot 2024-10-30 at 5 45 48 AM

The issue is still present on the main branch itself its not resolved and this files does not effect to this issue.

**Comment by Raj100** [comment]
The integrity code for may be bootstrap or some library is present without proper tag in this file.
 https://github.com/Vinay-Khanagavi/Cyberbear.github.io/blob/main/main/level_1/save_game.html 
Line no. 13

**Comment by Raj100** [comment]
Same true for other levels 
Screenshot 2024-10-30 at 5 55 44 AM

**Comment by Vinay-Khanagavi** [comment]
Because of accepting un reviewed PR made that happen, correct it and update The PR, I'll merge it

**Comment by Raj100** [comment]
Accept this Pr for that issue I will create other issue and PR

**Comment by Raj100** [comment]
Please add labels hacktober accepted and ggsoc ext labels

**Comment by Raj100** [comment]
@Vinay-Khanagavi Please add  hacktober accepted and ggsoc ext labels

**Comment by Raj100** [comment]
Please add hacktober accepted and ggsoc ext labels

**Comment by Raj100** [comment]
@Vinay-Khanagavi

**Pull request merged**
