### PR TITLE
added home buttons in all levels

### PR DESCRIPTION
**Pull request by SagarSharma2809**
I have added home buttons in all pages in all levels as discussed in Issue #92 

Please tell me if we need home buttons in the quiz pages too. I can add it to those pages as well. But, my thought process was that if user sees a home button in the quiz page, they would want to click it to escape the quiz and real learning hampers. 

image
image
image

### CODE REVIEW

**Comment by Vinay-Khanagavi** [comment]
Looks good, we'll review and merge it soon. Thanks for contribution

**Comment by B1N4RY-P4R45173** [comment]
@Vinay-Khanagavi can u look after this asap

**Comment by Vinay-Khanagavi** [comment]
> @Vinay-Khanagavi can u look after this asap

Yup working on it

**Comment by Vinay-Khanagavi** [comment]
looks good

**Review by Vinay-Khanagavi — COMMENTED** [review]
looks good

**Pull request merged**
