### PR TITLE
Add Translation Tool done ! #12

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Fixed issue - #12
Add new feature - Translation Tool

https://github.com/user-attachments/assets/3ffd43fd-49fc-4bce-a4d0-8cd7d295e00d

Screenshot 2024-10-14 221016

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Vinay-Khanagavi sir kindly add the level 3, because I made so many changes to properly add this feature.  Sir you can see my video/screenshot and code...

**Comment by Subhajit-2023-44** [comment]
@Vinay-Khanagavi

**Comment by Subhajit-2023-44** [comment]
> @Vinay-Khanagavi sir kindly add the level 3, because I made so many changes to properly add this new feature. Sir you can see my video/screenshot and code...

@Vinay-Khanagavi Sir its my last two work they gave me level 3 for this feature..

Screenshot 2024-10-15 202728

& I add Google Translate because It trusted, supports a vast number of languages, making it suitable for diverse audiences & Google continuously improves its translation algorithms, meaning your site benefits from these enhancements without additional work.

Sir please merge my PR & add level 3

**Comment by Vinay-Khanagavi** [comment]
I can't merge the PR yet, need to talk with my other member about this feature because the thing you added can also be added with translator tool provided by google and the place you added translation button should also need to change, you'll have to wait little longer for next response thank you

**Comment by Subhajit-2023-44** [comment]
> I can't merge the PR yet, need to talk with my other member about this feature because the thing you added can also be done with translator tool provided by google and the place you added translation button should also need to change, you'll have to wait little longer for next response thank you

@Vinay-Khanagavi Okay sir I am waiting

**Comment by aditichhawacharia** [comment]
hey @Subhajit-2023-44 will merge this i think its great but before you do, I actually made tons of html css changes to the homepage (it's just font and doesn't affect any code you did - you won't have to code anything) just please sync ur code to the new changes so the code I did doesn't get changed (since yours still has the old css)

**Comment by Subhajit-2023-44** [comment]
> hey @Subhajit-2023-44 will merge this i think its great but before you do, I actually made tons of html css changes to the homepage (it's just font and doesn't affect any code you did - you won't have to code anything) just please sync ur code to the new changes so the code I did doesn't get changed (since yours still has the old css)

Ok wait I'll give another PR..

**Comment by Subhajit-2023-44** [comment]
@Vinay-Khanagavi @aditichhawacharia please merge and add level 3 with gssoc-ext

#53

**Pull request closed without merging**
