### PR TITLE
Added Smooth Scrolling in B2T and Customize the Scrollbar | Issue #21

### PR DESCRIPTION
**Pull request by Shariq2003**
https://github.com/user-attachments/assets/f88f86c7-7b28-4170-a326-d96b59fe9ade

Completed #21

### CODE REVIEW

**Comment by Vinay-Khanagavi** [comment]
@Shariq2003 Looks good just change the scroll top button icon...  you can download icon from this URL 

https://www.flaticon.com/search?word=scroll%20top

**Note :** 

- It needs to be circular like the chatbot button 
- Should be in white or black theme color

**Comment by Shariq2003** [comment]
> @Shariq2003 Looks good just change the scroll top button icon... you can download icon from this URL
> 
> https://www.flaticon.com/search?word=scroll%20top
> 
> **Note :**
> 
> * It needs to be circular like the Chatbot button
> * Should be in white or black theme color
> * It's size should be similar to Chatbot button, I think you made it little bigger then before please correct it

okay sir

**Comment by Shariq2003** [comment]
@Vinay-Khanagavi sir check now


https://github.com/user-attachments/assets/b3ad6bf1-363b-4cfc-b2df-12b75652a27c

**Comment by Vinay-Khanagavi** [comment]
Thanks for the contribution

**Comment by Shariq2003** [comment]
@Vinay-Khanagavi u have added invalid tag

**Comment by Shariq2003** [comment]
Thanks sir

**Comment by Vinay-Khanagavi** [comment]
Yeah no problem.. join the discord server if you didn't yet

**Pull request merged**
