### PR TITLE
 Enhancements, fixes and UI/UX Improvements ISSUE#8

### PR DESCRIPTION
**Pull request by Talha-ai**
Overview
This PR focuses on making the application more engaging and approachable while improving the overall user experience. The updates include adjustments to text, question formatting, and UI elements to enhance usability and enjoyment.

Key Changes
1. Text and Fonts:
   - Updated text to be more friendly and light-hearted, removing any serious tone.
   - Selected playful fonts.
   
image

2. Improved Question Wording:
   - Revised the wording of questions for better clarity and understanding.

image

3. Explanations for Correct Answers:
   - Added explanations for correct answers when the user selects the wrong option.
      
image

4. Multiple Retry Options:
   - Implemented functionality allowing users to retry questions multiple times (a total of 2 times).
   
   image

5. Redirect on loss:
   - Redirected to phishing_awareness page instead of failed page. 

6. UI/UX Improvements:
   - Made various UI/UX enhancements to create a more visually appealing and intuitive experience for users.

### CODE REVIEW

**Comment by B1N4RY-P4R45173** [comment]
lgtm, might need some advancements in UI design but I am not sure about the redirection to phishing awareness page. I really liked the design and the sound of mission failed page. 🙃

**Comment by Talha-ai** [comment]
> lgtm, might need some advancements in UI design but I am not sure about the redirection to phishing awareness page. I really liked the design and the sound of mission failed page. 🙃

Could you clarify what type of advancements you’re looking for in the UI? Regarding the redirection from the failed page, I also like the current design, but it was mentioned in the issue that the redirection should lead to the explanation page.

**Comment by B1N4RY-P4R45173** [comment]
> Could you clarify what type of advancements you’re looking for in the UI? Regarding the redirection from the failed page, I also like the current design, but it was mentioned in the issue that the redirection should lead to the explanation page.

The reviewers will let you know Most of things should be fine, they might suggest some minute changes

**Comment by B1N4RY-P4R45173** [comment]
Also @Talha-ai are u participating in gssoc?

**Comment by aditichhawacharia** [comment]
Yes I love it!

**Review by aditichhawacharia — COMMENTED** [review]
It's really great - this is exactly what I wanted it to be, the fonts, the descriptions, and the convenience it's extremely kid friendly and professional Good job!

**Pull request merged**
