### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AnujShrivastava01**
#### - Includes svg and Animation effects
image

### Thankyou !!

### CODE REVIEW

**Comment by B1N4RY-P4R45173** [comment]
Please join our discord server. We can discuss abt this there

**Comment by Vinay-Khanagavi** [comment]
image
 Correct the spelling... it's github not gihub

**Comment by AnujShrivastava01** [comment]
### Done !!
image

**Comment by AnujShrivastava01** [comment]
@Vinay-Khanagavi 
Please Review and Merge the by assigning it to me and giving gssoc-ext and level2 label !

**Comment by Vinay-Khanagavi** [comment]
Actually, We don't want that - welcome message , emojies

add this tag too..

image

**Pull request closed without merging**
